## Interest Rates and Bond Performance

Interest rates reflect the cost of borrowing money, and they are a critical part of the economic system. In many developed countries there is a base interest rate, which is used as a benchmark rate. Said interest rate is determined by the central banks of the respective countries, and they lower or raise this instrument according to their monetary policy.

The decision of what to do relating the interest rates depends highly on the levels of inflation and growth of the country. Thus, if the levels of inflation and growth are high, interest rates will probably be raised in order to decrement consumption of goods and services. This often prompts retail banks to raise the rates at which they lend, pushing up the cost of borrowing. Banks may also raise their deposit rates, which makes savings more attractive.

On the other hand, if the economy is slowing, the central bank may reduce the base rate. In turn, retail banks may lower their rates making it more attractive to borrow and spend money but less attractive to save it.